FROM ubuntu:20.04
LABEL maintainer="Melnikov_D_M"
COPY . /MyProj_211_351_Melnikov_D_M
WORKDIR /MyProj_211_351_Melnikov_D_M

RUN apt update
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y gcc
RUN apt-get -y install build-essential

RUN apt-get update && \
    apt-get install -y \
      libboost-dev libboost-program-options-dev \
      libgtest-dev \
      cmake \
    && \
    cmake -DCMAKE_BUILD_TYPE=Release /usr/src/gtest && \
    cmake --build . && \
    mv lib*.a /usr/lib

RUN cmake MyProgram.sln
RUN make

ENTRYPOINT ["./MyProgram"]

